### ISSUE TITLE
Output getting cut

### ISSUE THREAD

**Issue by Infinitay** [vyneer/tbf#2]
![image](https://user-images.githubusercontent.com/6964154/188334807-e535590a-5eb9-40ab-b746-9d72335310ae.png)

As you can see from the image, stdout is getting cut after the first link it finds. I've noticed this happens a lot when there are multiple links found. The last link is the one that tends to get cut from my recollection.

**Comment by vyneer** [comment]
I think I fixed it in the latest release (not exactly sure what precisely was the issue, but whatever)

Test it out and let me know/close the issue if it's fixed <3

**Comment by Infinitay** [comment]
You fixed it, but brought another issue. Now the window closes despite not having it as an active window and doing any sort of IO whether it's keyboard or mouse.

Case 1: Minimized tbf while it was searching. I about using my computer as per usual and noticed the window suddenly disappeared.
Case 2: Left tbf opened while it was searching. Upon finishing the search, I clicked anywhere on my screen not in the terminal and it just closed.

**Comment by vyneer** [comment]
Ah, I think I found the issue: the crossterm library added the ```FocusGained``` and ```FocusLost``` events in the [0.25.0 update](https://docs.rs/crossterm/0.25.0/crossterm/event/enum.Event.html), and since my ```any_key_to_continue``` function just fires on any event, it closed the program on resize/focus change/etc.

Edit: Hopefully fixed in https://github.com/vyneer/tbf/commit/629d87f523d369476413d60f4b5e8a2ae79070b9

**Comment by Infinitay** [comment]
Seems resolves now, thank you.

**Comment by Infinitay** [comment]
Seems like this is still happening whenever you get the following error,
> Got the URL and it was NOT available on Twitch servers :(

Same issue as above where the window doesn't have to be focused but it will still listen for any events.

**Comment by vyneer** [comment]
I can't seem to reproduce it:

https://user-images.githubusercontent.com/41237021/189074161-037b9e06-ed67-46d1-9c5a-62216f5e3a9e.mp4

Could you provide the specific URL you were trying out (or just the specific arguments, if you used a different function)? Might be something else that's unrelated to the event thing.

**Comment by Infinitay** [comment]
URL: `https://streamscharts.com/channels/robcdee/streams/46104241165`

https://user-images.githubusercontent.com/6964154/189077119-d019963b-c85c-4978-8589-f60a275bf921.mp4

Didn't do anything in the video after it prompted me for input except click its entry within task manager. To clarify, no keyboard inputs either.

**Comment by vyneer** [comment]
Ah, I think I know what's up! You're using your PR branch with the StreamsCharts timestamp changes, but it doesn't have the commit that fixed the issue Hhhhehehehe

https://github.com/Infinitay/tbf/blob/streamscharts-exact-timestamps/src/util.rs#L69 vs https://github.com/vyneer/tbf/blob/main/src/util.rs#L57

**Comment by Infinitay** [comment]
The issue is on my end. I forgot that I re-downloaded the GitHub release and that it wasn't from the most recent commit that fixed this. Furthermore, when I tested it with my branch with the new exact timestamp feature, I noticed just now that my branch wasn't up to date either. Just fetched and rebased and is working just fine.

My apologies.

**Comment by vyneer** [comment]
No worries! ❤️
